### ISSUE TITLE
Feature suggestion: global tags

### ISSUE THREAD

**Issue by dtjohnso** [alnorth/rtm-bulk-adder#1]
Would it be possible to add a field that would allow tags or other items to be added to each task in a list submitted to RTM?

For instance, I use this regularly to submit a wack of tasks to my #Work list. If I didn't have to remember to type "#Work" into the Smart Add syntax for each task it would help me out immensely. Sometimes I forget on one or two tasks, and then they get lost in my Inbox list, which I don't check as often.

Anyway, if that's doable, I'd be interested in seeing it.

**Comment by alnorth** [comment]
Sounds like a good idea, and very easy to do. I'll add this at the weekend if I have time.

**Comment by alnorth** [comment]
This has now been implemented :)
